### ISSUE TITLE
Store LOM and Passthrough MAC Addresses for all laptops/desktops/all-in-ones

### ISSUE THREAD

**Issue by JustATechie** [USS-IT/SnipeITWinSync#12]
Currently these fields are not stored in snipe-it, but if they fall off the network we have to grab it from the system settings if the system is imaged, or boot into the bios and find the information to register in jhars.

**Comment by mcarras8** [comment]
Latest import has these new custom fields filled out. See "Create All-in-one SCCM/JHARS/Snipe-It import script".
