### ISSUE TITLE
Change Mac Checkboxes to Apple Checkboxes

### ISSUE THREAD

**Issue by JustATechie** [USS-IT/SnipeITWinSync#7]

**Comment by mcarras8** [comment]
@JustATechie Was this change already made? I noticed some errors in the PBI reports about the "Mac Checkboxes" field name changing.

**Comment by JustATechie** [comment]
> @JustATechie Was this change already made? I noticed some errors in the PBI reports about the "Mac Checkboxes" field name changing.

I did already update the name. My bad, I didn't realize power BI would have issues with this.
